#!/usr/bin/env ruby

require "thor"
require "passe"
require "passe/cli"
require 'passe/outputter/ascii_outputter'

pattern = Passe.root.join("lib", "passe", "outputter", "*.rb")
Dir.glob(pattern){|f| require "passe/outputter/#{File.basename(f, '.rb')}"}

# version = "Passe v#{Passe::VERSION} - Generate password grids with ease."
begin
  Passe::CLI.start(ARGV)
rescue Passe::Error => e
  STDERR.puts "\x1b[31m[Passe] Error: #{e.message}\x1b[0m"
  exit 1
rescue StandardError => e
  STDERR.puts "\x1b[31m[#{e.class}] FATAL: #{e.message}\x1b[0m"
  STDERR.puts e.backtrace.join("\n  ")
  exit 2
end
